/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author abdelhady
 */
public class frameCalculator extends javax.swing.JFrame {

    /**
     * Creates new form frameCalculator
     */
    public frameCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField = new javax.swing.JTextField();
        botton0 = new javax.swing.JButton();
        botton1 = new javax.swing.JButton();
        botton2 = new javax.swing.JButton();
        botton3 = new javax.swing.JButton();
        botton4 = new javax.swing.JButton();
        botton5 = new javax.swing.JButton();
        botton6 = new javax.swing.JButton();
        botton7 = new javax.swing.JButton();
        botton8 = new javax.swing.JButton();
        botton9 = new javax.swing.JButton();
        bottonDot = new javax.swing.JButton();
        bottonEquel = new javax.swing.JButton();
        bottonPlus = new javax.swing.JButton();
        bottonMinus = new javax.swing.JButton();
        bottonTimes = new javax.swing.JButton();
        bottonDivid = new javax.swing.JButton();
        bottonSign = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TextField.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N

        botton0.setText("0");
        botton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton0ActionPerformed(evt);
            }
        });

        botton1.setText("1");
        botton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton1ActionPerformed(evt);
            }
        });

        botton2.setText("2");
        botton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton2ActionPerformed(evt);
            }
        });

        botton3.setText("3");
        botton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton3ActionPerformed(evt);
            }
        });

        botton4.setText("4");
        botton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton4ActionPerformed(evt);
            }
        });

        botton5.setText("5");
        botton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton5ActionPerformed(evt);
            }
        });

        botton6.setText("6");
        botton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton6ActionPerformed(evt);
            }
        });

        botton7.setText("7");
        botton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton7ActionPerformed(evt);
            }
        });

        botton8.setText("8");
        botton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton8ActionPerformed(evt);
            }
        });

        botton9.setText("9");
        botton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton9ActionPerformed(evt);
            }
        });

        bottonDot.setText(".");
        bottonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonDotActionPerformed(evt);
            }
        });

        bottonEquel.setText("=");
        bottonEquel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonEquelActionPerformed(evt);
            }
        });

        bottonPlus.setText("+");
        bottonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonPlusActionPerformed(evt);
            }
        });

        bottonMinus.setText("-");
        bottonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonMinusActionPerformed(evt);
            }
        });

        bottonTimes.setText("X");
        bottonTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonTimesActionPerformed(evt);
            }
        });

        bottonDivid.setText("/");
        bottonDivid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonDividActionPerformed(evt);
            }
        });

        bottonSign.setText("Sign");
        bottonSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonSignActionPerformed(evt);
            }
        });

        ButtonClear.setBackground(new java.awt.Color(255, 255, 255));
        ButtonClear.setText("clear");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        ButtonClose.setBackground(new java.awt.Color(255, 0, 0));
        ButtonClose.setForeground(new java.awt.Color(255, 255, 255));
        ButtonClose.setText("Close");
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bottonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bottonTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bottonSign, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bottonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bottonDivid, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(bottonEquel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botton0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bottonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(botton7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botton8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(botton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(botton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bottonSign, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bottonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bottonTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botton0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottonEquel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bottonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottonDivid, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened
    
    double operandOne;
    double operandTow;
    double result;
    char oparetor;
    
    private void ButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonCloseActionPerformed
    private void setOperandOne(char ope) {
        operandOne = Double.parseDouble(TextField.getText());
        oparetor = ope;
        TextField.setText("");
    }
    private void setTextField(String val) {
        TextField.setText(TextField.getText() + val);
    } 
    
    private void botton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton0ActionPerformed
        // TODO add your handling code here:
        setTextField("0");
    }//GEN-LAST:event_botton0ActionPerformed

    private void botton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton1ActionPerformed
        // TODO add your handling code here:
        setTextField("1");
    }//GEN-LAST:event_botton1ActionPerformed

    private void botton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton2ActionPerformed
        // TODO add your handling code here:
        setTextField("2");
    }//GEN-LAST:event_botton2ActionPerformed

    private void botton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton3ActionPerformed
        // TODO add your handling code here:
        setTextField("3");
    }//GEN-LAST:event_botton3ActionPerformed

    private void botton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton4ActionPerformed
        // TODO add your handling code here:
        setTextField("4");
    }//GEN-LAST:event_botton4ActionPerformed

    private void botton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton5ActionPerformed
        // TODO add your handling code here:
        setTextField("5");
    }//GEN-LAST:event_botton5ActionPerformed

    private void botton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton6ActionPerformed
        // TODO add your handling code here:
        setTextField("5");
    }//GEN-LAST:event_botton6ActionPerformed

    private void botton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton7ActionPerformed
        // TODO add your handling code here:
        setTextField("7");
    }//GEN-LAST:event_botton7ActionPerformed

    private void botton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton8ActionPerformed
        // TODO add your handling code here:
        setTextField("8");
    }//GEN-LAST:event_botton8ActionPerformed

    private void botton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton9ActionPerformed
        // TODO add your handling code here:
        setTextField("9");
    }//GEN-LAST:event_botton9ActionPerformed

    private void bottonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonDotActionPerformed
        // TODO add your handling code here:
        setTextField(".");
    }//GEN-LAST:event_bottonDotActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        // TODO add your handling code here:
        TextField.setText("");
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void bottonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonPlusActionPerformed
        // TODO add your handling code here:
        setOperandOne('+');
        
    }//GEN-LAST:event_bottonPlusActionPerformed

    private void bottonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonMinusActionPerformed
        // TODO add your handling code here:
        setOperandOne('-');
    }//GEN-LAST:event_bottonMinusActionPerformed

    private void bottonTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonTimesActionPerformed
        // TODO add your handling code here:
        setOperandOne('X');
    }//GEN-LAST:event_bottonTimesActionPerformed

    private void bottonDividActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonDividActionPerformed
        // TODO add your handling code here:
        setOperandOne('/');
    }//GEN-LAST:event_bottonDividActionPerformed

    private void bottonSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonSignActionPerformed
        // TODO add your handling code here:
        double number = Double.parseDouble(TextField.getText());
        number *= -1;
        TextField.setText(String.valueOf(number));
    }//GEN-LAST:event_bottonSignActionPerformed

    private void bottonEquelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonEquelActionPerformed
        // TODO add your handling code here:
        int notDivid = 0;
        operandTow = Double.parseDouble(TextField.getText());
        switch (oparetor) {
            case '+': result = operandOne + operandTow; break;
            case '-': result = operandOne - operandTow; break;
            case 'X': result = operandOne * operandTow; break;
            case '/':
                if (operandTow != 0)
                    result = operandOne / operandTow;
                else {
                    notDivid = 1;
                    TextField.setText("ERROR"); 
                }
                 break;
        }
        if (notDivid != 1)
            TextField.setText(String.valueOf(result));
        
        
    }//GEN-LAST:event_bottonEquelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonClose;
    private javax.swing.JTextField TextField;
    private javax.swing.JButton botton0;
    private javax.swing.JButton botton1;
    private javax.swing.JButton botton2;
    private javax.swing.JButton botton3;
    private javax.swing.JButton botton4;
    private javax.swing.JButton botton5;
    private javax.swing.JButton botton6;
    private javax.swing.JButton botton7;
    private javax.swing.JButton botton8;
    private javax.swing.JButton botton9;
    private javax.swing.JButton bottonDivid;
    private javax.swing.JButton bottonDot;
    private javax.swing.JButton bottonEquel;
    private javax.swing.JButton bottonMinus;
    private javax.swing.JButton bottonPlus;
    private javax.swing.JButton bottonSign;
    private javax.swing.JButton bottonTimes;
    // End of variables declaration//GEN-END:variables
}
